site_name: Picturate
theme:
  name: "material"
  palette:
    primary: "blue"
    accent: "blue"

docs_dir: sources
repo_url: https://github.com/picturate/picturate
site_url: https://picturate.github.io/picturate/
edit_uri: ""
site_description: 'Documentation for Picturate.'
markdown_extensions:
  - codehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
extra_javascript:
  - https://unpkg.com/mermaid@8.4.4/dist/mermaid.min.js

nav:
  - Home: index.md